name: collection_extensions
description: A dart library that adds some extensions to Iterables.
version: 1.0.0
repository: https://github.com/Bdaya-Dev/dart-collection-extensions

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety